language: node_js
node_js:
- '8.11'
branches:
  only:
  - master
before_script:
- npm install -g firebase-tools
- npm install -g @angular/cli
script:
- ng build --prod
after_success:
- firebase deploy --token $FIREBASE_TOKEN
notifications:
  email:
    on_failure: change
    on_success: change
deploy:
  provider: heroku
  app: accedo-test-2018
  api_key:
    secure: mhv4kt4xJBMzgW3f42D26+4x9Q/LbyEh1B8CU8MAK3g8yDCkn1Mm0K8BPJfuxczt55CjsLBUupN4dvwxOlL1eeFRtM5qDqaV9uLhYCvwHDQU9e4tODpFHMej5pj3OTRnJMsjRi/ZS+tTEWOUGk/l8o9+21geOyMnHhpkZ+eohpysKrXuCbRGa8UUelh7FwtgZ/0jmBlVnXnxJn/7APqlQ/xHeTP+fp+hLM1whbzFP3VL716/xufIVim8EwOP/W1aACq2aani+NEzD9YPmSRD3SOMpLqFqTzJCuL5BdxH92oaznbshg7i/PBqSHl+IeIXqlLMSAJuzzxGo6SjUnG795tFhz7ruVzCKVTyJCbxzAKPvTCvAYb3izJFGUTOuK47NZimH0wLO3HUrtGoeq4HdD4Q48e93Sg44F5oULxHgt1O+CKzA2xBMAArVvIfefvdxYhVWPQb1cLHPKGJ3NGwOoIaqi07T7T58ZgPU5fUeBf8wNk0U6TbqtST5Ep234+R2vh2vKcsqnLVhv3oezZcPGQtcxcxHsJCMNSpnOCC+7TPRLfbyZzc3u+ZXrXKskyi1jnKm4Wv8fbCZa8AtrFbYq0+iXSq3d0YMH6w9TLV7U8aqBD+o9Y3uEiBAXVkGwc6eBINCL8Xg6iUicSmjsa9LBe53K/qzjVHL0+Pm43d6wc=
